import { PageColorTheme } from '@/components/layout/DashboardPageWrapper';

export const pageThemes: Record<string, PageColorTheme> = {
  'claude-assistant': {
    bgFrom: 'from-indigo-50',
    bgVia: 'via-purple-50',
    bgTo: 'to-pink-50',
    headerFrom: 'from-indigo-600',
    headerTo: 'to-purple-600',
    buttonFrom: 'from-indigo-500',
    buttonTo: 'to-purple-600',
    iconBg: 'bg-indigo-100',
    iconColor: 'text-indigo-600',
    borderColor: 'border-indigo-100',
  },
  'articles': {
    bgFrom: 'from-sky-50',
    bgVia: 'via-blue-50',
    bgTo: 'to-indigo-50',
    headerFrom: 'from-sky-600',
    headerTo: 'to-indigo-600',
    buttonFrom: 'from-sky-500',
    buttonTo: 'to-indigo-600',
    iconBg: 'bg-sky-100',
    iconColor: 'text-sky-600',
    borderColor: 'border-sky-100',
  },
  'scripts': {
    bgFrom: 'from-violet-50',
    bgVia: 'via-purple-50',
    bgTo: 'to-fuchsia-50',
    headerFrom: 'from-violet-600',
    headerTo: 'to-purple-600',
    buttonFrom: 'from-violet-500',
    buttonTo: 'to-purple-600',
    iconBg: 'bg-violet-100',
    iconColor: 'text-violet-600',
    borderColor: 'border-violet-100',
  },
  'emails': {
    bgFrom: 'from-emerald-50',
    bgVia: 'via-green-50',
    bgTo: 'to-teal-50',
    headerFrom: 'from-emerald-600',
    headerTo: 'to-teal-600',
    buttonFrom: 'from-emerald-500',
    buttonTo: 'to-teal-600',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-600',
    borderColor: 'border-emerald-100',
  },
  'posts': {
    bgFrom: 'from-pink-50',
    bgVia: 'via-rose-50',
    bgTo: 'to-fuchsia-50',
    headerFrom: 'from-pink-600',
    headerTo: 'to-fuchsia-600',
    buttonFrom: 'from-pink-500',
    buttonTo: 'to-fuchsia-600',
    iconBg: 'bg-pink-100',
    iconColor: 'text-pink-600',
    borderColor: 'border-pink-100',
  },
  'stories': {
    bgFrom: 'from-orange-50',
    bgVia: 'via-amber-50',
    bgTo: 'to-yellow-50',
    headerFrom: 'from-orange-600',
    headerTo: 'to-amber-600',
    buttonFrom: 'from-orange-500',
    buttonTo: 'to-amber-600',
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-600',
    borderColor: 'border-orange-100',
  },
  'summaries': {
    bgFrom: 'from-indigo-50',
    bgVia: 'via-slate-50',
    bgTo: 'to-slate-50',
    headerFrom: 'from-indigo-600',
    headerTo: 'to-slate-700',
    buttonFrom: 'from-indigo-500',
    buttonTo: 'to-slate-600',
    iconBg: 'bg-indigo-100',
    iconColor: 'text-indigo-600',
    borderColor: 'border-indigo-100',
  },
  'protocols': {
    bgFrom: 'from-teal-50',
    bgVia: 'via-cyan-50',
    bgTo: 'to-sky-50',
    headerFrom: 'from-teal-600',
    headerTo: 'to-sky-600',
    buttonFrom: 'from-teal-500',
    buttonTo: 'to-sky-600',
    iconBg: 'bg-teal-100',
    iconColor: 'text-teal-600',
    borderColor: 'border-teal-100',
  },
  'worksheets': {
    bgFrom: 'from-amber-50',
    bgVia: 'via-orange-50',
    bgTo: 'to-rose-50',
    headerFrom: 'from-amber-600',
    headerTo: 'to-rose-600',
    buttonFrom: 'from-amber-500',
    buttonTo: 'to-rose-600',
    iconBg: 'bg-amber-100',
    iconColor: 'text-amber-600',
    borderColor: 'border-amber-100',
  },
  'prompts': {
    bgFrom: 'from-purple-50',
    bgVia: 'via-indigo-50',
    bgTo: 'to-blue-50',
    headerFrom: 'from-purple-600',
    headerTo: 'to-blue-600',
    buttonFrom: 'from-purple-500',
    buttonTo: 'to-blue-600',
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-600',
    borderColor: 'border-purple-100',
  },
  'languages': {
    bgFrom: 'from-teal-50',
    bgVia: 'via-blue-50',
    bgTo: 'to-purple-50',
    headerFrom: 'from-teal-600',
    headerTo: 'to-purple-600',
    buttonFrom: 'from-teal-500',
    buttonTo: 'to-purple-600',
    iconBg: 'bg-teal-100',
    iconColor: 'text-teal-600',
    borderColor: 'border-teal-100',
  },
  'flip-document': {
    bgFrom: 'from-slate-50',
    bgVia: 'via-gray-50',
    bgTo: 'to-zinc-50',
    headerFrom: 'from-slate-600',
    headerTo: 'to-zinc-600',
    buttonFrom: 'from-slate-500',
    buttonTo: 'to-zinc-600',
    iconBg: 'bg-slate-100',
    iconColor: 'text-slate-600',
    borderColor: 'border-slate-100',
  },
  'transcription-guidelines': {
    bgFrom: 'from-yellow-50',
    bgVia: 'via-amber-50',
    bgTo: 'to-orange-50',
    headerFrom: 'from-yellow-600',
    headerTo: 'to-orange-600',
    buttonFrom: 'from-yellow-500',
    buttonTo: 'to-orange-600',
    iconBg: 'bg-yellow-100',
    iconColor: 'text-yellow-600',
    borderColor: 'border-yellow-100',
  },
  'research': {
    bgFrom: 'from-blue-50',
    bgVia: 'via-indigo-50',
    bgTo: 'to-purple-50',
    headerFrom: 'from-blue-600',
    headerTo: 'to-purple-600',
    buttonFrom: 'from-blue-500',
    buttonTo: 'to-purple-600',
    iconBg: 'bg-blue-100',
    iconColor: 'text-blue-600',
    borderColor: 'border-blue-100',
  },
  'legal-cases': {
    bgFrom: 'from-purple-50',
    bgVia: 'via-purple-50',
    bgTo: 'to-indigo-50',
    headerFrom: 'from-purple-600',
    headerTo: 'to-indigo-600',
    buttonFrom: 'from-purple-500',
    buttonTo: 'to-indigo-600',
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-600',
    borderColor: 'border-purple-100',
  },
  'code-review': {
    bgFrom: 'from-cyan-50',
    bgVia: 'via-blue-50',
    bgTo: 'to-indigo-50',
    headerFrom: 'from-cyan-600',
    headerTo: 'to-indigo-600',
    buttonFrom: 'from-cyan-500',
    buttonTo: 'to-indigo-600',
    iconBg: 'bg-cyan-100',
    iconColor: 'text-cyan-600',
    borderColor: 'border-cyan-100',
  },
  'content-improvement': {
    bgFrom: 'from-emerald-50',
    bgVia: 'via-teal-50',
    bgTo: 'to-cyan-50',
    headerFrom: 'from-emerald-600',
    headerTo: 'to-cyan-600',
    buttonFrom: 'from-emerald-500',
    buttonTo: 'to-cyan-600',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-600',
    borderColor: 'border-emerald-100',
  },
  'quotes': {
    bgFrom: 'from-yellow-50',
    bgVia: 'via-amber-50',
    bgTo: 'to-orange-50',
    headerFrom: 'from-yellow-600',
    headerTo: 'to-orange-600',
    buttonFrom: 'from-yellow-500',
    buttonTo: 'to-orange-600',
    iconBg: 'bg-yellow-100',
    iconColor: 'text-yellow-600',
    borderColor: 'border-yellow-100',
  },
  'ai-correction': {
    bgFrom: 'from-violet-50',
    bgVia: 'via-purple-50',
    bgTo: 'to-fuchsia-50',
    headerFrom: 'from-violet-600',
    headerTo: 'to-fuchsia-600',
    buttonFrom: 'from-violet-500',
    buttonTo: 'to-fuchsia-600',
    iconBg: 'bg-violet-100',
    iconColor: 'text-violet-600',
    borderColor: 'border-violet-100',
  },
  'default': {
    bgFrom: 'from-slate-50',
    bgVia: 'via-gray-50',
    bgTo: 'to-zinc-50',
    headerFrom: 'from-slate-600',
    headerTo: 'to-zinc-600',
    buttonFrom: 'from-slate-500',
    buttonTo: 'to-zinc-600',
    iconBg: 'bg-slate-100',
    iconColor: 'text-slate-600',
    borderColor: 'border-slate-100',
  },
};

export function getPageTheme(pageName: string): PageColorTheme {
  return pageThemes[pageName] || pageThemes['default'];
}
